#!/bin/sh

usage() {
	printf "$(basename $0) [OPTIONS] <input>.md\n"
	printf "OPTIONS:\n"
	printf "  -H, --style <file>.tex\n"
	printf "  -l, --lua-filter <file>.lua\n"
    printf "  -o, --output <file>\n"
}

md2pdf_path=$(dirname $(readlink -f $0))
style_path=$md2pdf_path"/style.tex"
highlight_style_path="$md2pdf_path/tango-grey-bg.theme"

while [ $# -gt 1 ]; do
    case "$1" in
        --style-file|-H)
            shift
            style_path="$(readlink -f "$1")"
            shift
            ;;
        --lua-filter|-l)
            shift
            lua_filter_path="$(readlink -f "$1")"
            shift
            ;;
        --output|-o)
            shift
            output="$1"
            shift
            ;;
        *)
            shift
            ;;
    esac
done

[ -z "$1" ] && usage && exit 1

filename=$(echo "$1" | sed 's/\.[^.]*$//')
extension=$(echo "$1" | sed 's/^.*\.//')

echo "* input file: \`$(realpath --relative-to=$HOME $1)\`"
echo "* style file: \`$(realpath --relative-to=$HOME $style_path)\`"
[ ! -z "$lua_filter_path" ] && echo "* lua filter: \`$(realpath --relative-to=$HOME $lua_filter_path)\`" &&\
    lua_filter="--lua-filter=$lua_filter_path"
echo "* highlight style file: \`$(realpath --relative-to=$HOME $highlight_style_path)\`"

[ -z "$output" ] && output="$filename.pdf"
input_format="markdown+startnum+tex_math_dollars+implicit_figures"\
"+grid_tables+backtick_code_blocks"

[ "$extension" != "md" ] && \
	echo "Input file not markdown" && \
	usage && exit 2

pandoc --pdf-engine=xelatex \
	-V colorlinks=true \
	-V linkcolor=blue \
	-V urlcolor=blue \
	-H $style_path \
	-f $input_format \
	--highlight-style "$highlight_style_path" \
	--shift-heading-level-by=-1 \
	-o "$output" \
    $lua_filter \
	"$filename".md

[ $? -ne 0 ] && exit 3

printf "\`$output\` generated successfully\n"
